# Uncomment the next line to define a global platform for your project
# platform :ios, '12.1'

target 'FirstSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sample

end

plugin 'cocoapods-keys', {
    :project => "FirstSample",
    :target => ["FirstSample"],
    :keys => ["FirstSampleKey", "SecondaryFirstSampleKey"]
}
