# Uncomment the next line to define a global platform for your project
# platform :ios, '12.1'

target 'Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sample

end

plugin 'cocoapods-keys', {
    :project => "Sample",
    :target => ["Sample"],
    :keys => ["SampleKey", "SecondarySampleKey"]
}
